In [1]:
gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)

Fri Jul 28 01:14:36 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

In [2]:
from psutil import virtual_memory
ram_gb = virtual_memory().total / 1e9
print('Your runtime has {:.1f} gigabytes of available RAM\n'.format(ram_gb))

if ram_gb < 20:
  print('Not using a high-RAM runtime')
else:
  print('You are using a high-RAM runtime!')

Your runtime has 27.3 gigabytes of available RAM

You are using a high-RAM runtime!

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
#import pandas_datareader as pdr
from datetime import datetime,timedelta
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense ,LSTM, Dropout,Bidirectional,TimeDistributed
from sklearn.model_selection import train_test_split, KFold
from tensorflow import expand_dims
from tensorflow.keras.losses import Huber
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
from os.path import join
from tensorflow import constant
from time import sleep
from prophet import Prophet
import tensorflow as tf

#import FinanceDataReader as fdr

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
data=pd.read_csv('/content/drive/MyDrive/2023_1st_vac/KRX_DATA/train.csv')

In [ ]:
gl=pd.read_csv('/content/drive/MyDrive/2023_1st_vac/KRX_DATA/goldlee.csv')

In [ ]:
def convert_date(date_str):
  return pd.to_datetime(date_str, format="%Y%m%d").strftime("%Y-%m-%d")
data["일자"] =data["일자"].apply(convert_date)

In [ ]:
def convert_date(date_str):
  return pd.to_datetime(date_str, format="%Y/%m/%d").strftime("%Y-%m-%d")
gl["일자"] =gl["일자"].apply(convert_date)

In [ ]:
gl = gl[gl["일자"].isin(data["일자"].unique())]
gl.set_index('일자',inplace=True)

In [ ]:
# prescaler
def getAOC(data):
  AOC = []
  close = data['종가']
  close_pre = close.shift(1)

  AOC.append(0)

  # aoc = (금일 종가 - 전일 종가) / 전일 종가
  for i in range(1, len(close)):
    aoc_value = ((close[i] - close_pre[i]) / close_pre[i]) * 100
    AOC.append(aoc_value)

  return AOC

#sort data by "종목명"
subject_Data=data.sort_values(by="종목코드",inplace=False)
subject_Data.head()
subject_Data.columns


pv_s_data=pd.pivot_table(subject_Data,values=['거래량', '시가', '고가', '저가', '종가'],index=['종목코드','일자'])
pv_s_data["AOC"] = getAOC(pv_s_data)

divided = pv_s_data.index.get_level_values('종목코드').unique()

dataframes = []

for i in divided:
    sliced_data = pv_s_data.loc[i]
    sliced_dataframe = sliced_data.reset_index()
    dataframes.append(sliced_dataframe)

sliced_dataframes=[]

for s in dataframes:
    end = s.pop('종가')
    sliced_dataframe = pd.merge(s, gl, left_on='일자', right_index=True, how='left')
    sliced_dataframe['종가'] = end
    sliced_dataframes.append(sliced_dataframe)

In [ ]:
data

                일자     종목코드     종목명      거래량     시가     고가     저가     종가
0       2021-06-01  A060310      3S   166690   2890   2970   2885   2920
1       2021-06-01  A095570  AJ네트웍스    63836   5860   5940   5750   5780
2       2021-06-01  A006840   AK홀딩스   103691  35500  35600  34150  34400
3       2021-06-01  A054620     APS   462544  14600  14950  13800  14950
4       2021-06-01  A265520   AP시스템   131987  29150  29150  28800  29050
...            ...      ...     ...      ...    ...    ...    ...    ...
987995  2023-05-30  A189980  흥국에프엔비   272284   3005   3035   2955   2980
987996  2023-05-30  A000540    흥국화재    50218   3250   3255   3195   3215
987997  2023-05-30  A003280    흥아해운   130664   1344   1395   1340   1370
987998  2023-05-30  A037440      희림   141932   9170   9260   9170   9200
987999  2023-05-30  A238490      힘스  2611843   6410   8220   6300   8220

[988000 rows x 8 columns]

In [ ]:
test=sliced_dataframes[1999]
test

,일자,거래량,고가,시가,저가,AOC,한국은행 기준금리,정부대출금금리,무역금융지원 프로그램대출금리,영세자영업자지원 프로그램대출금리,신성장·일자리지원 프로그램대출금리,설비투자지원 프로그램대출금리,지방중소기업지원 프로그램대출금리,자금조정 대출금리,자금조정 예금금리,종가
0,2021-06-01,1879288,11300,11000,10900,-82.258065,0.5,0.601,0.25,0.25,0.25,0.25,0.25,1.0,0.0,11000
1,2021-06-02,2426922,10850,10700,10600,-2.727273,0.5,0.601,0.25,0.25,0.25,0.25,0.25,1.0,0.0,10700
2,2021-06-03,2709800,10700,10650,10300,-2.803738,0.5,0.601,0.25,0.25,0.25,0.25,0.25,1.0,0.0,10400
3,2021-06-04,1737593,10650,10450,10350,0.480769,0.5,0.601,0.25,0.25,0.25,0.25,0.25,1.0,0.0,10450
4,2021-06-07,2714980,11150,10550,10500,3.349282,0.5,0.601,0.25,0.25,0.25,0.25,0.25,1.0,0.0,10800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
489,2023-05-23,150364,8390,8390,8310,-0.358852,3.5,3.534,2.00,2.00,2.00,2.00,2.00,4.5,2.5,8330
490,2023-05-24,122457,8340,8310,8280,-0.360144,3.5,3.534,2.00,2.00,2.00,2.00,2.00,4.5,2.5,8300
491,2023-05-25,84241,8310,8300,8270,0.120482,3.5,3.534,2.00,2.00,2.00,2.00,2.00,4.5,2.5,8310
492,2023-05-26,126681,8310,8300,8270,-0.361011,3.5,3.534,2.00,2.00,2.00,2.00,2.00,4.5,2.5,8280
493,2023-05-30,70489,8300,8300,8270,0.120773,3.5,3.534,2.00,2.00,2.00,2.00,2.00,4.5,2.5,8290

In [ ]:
## sorting labels
labels=data[['종목코드','일자']]
labels = labels.sort_values(by=['종목코드','일자'])
labels=labels.drop('일자',axis=1)
labels=labels.drop_duplicates('종목코드')
data.sort_values(by=['종목코드',"일자"],inplace=True)

In [ ]:
label_lis=[]
for label in labels:
  label_lis.append(label)

In [ ]:
for sliced in sliced_dataframes:
  sliced.drop('일자',axis=1,inplace=True)

In [ ]:
sliced_dataframes[0]

,거래량,고가,시가,저가,AOC,한국은행 기준금리,정부대출금금리,무역금융지원 프로그램대출금리,영세자영업자지원 프로그램대출금리,신성장·일자리지원 프로그램대출금리,설비투자지원 프로그램대출금리,지방중소기업지원 프로그램대출금리,자금조정 대출금리,자금조정 예금금리,종가
0,114966,14700,14700,14450,0.000000,0.5,0.601,0.25,0.25,0.25,0.25,0.25,1.0,0.0,14600
1,109559,14700,14700,14450,-0.684932,0.5,0.601,0.25,0.25,0.25,0.25,0.25,1.0,0.0,14500
2,96158,14650,14550,14450,0.689655,0.5,0.601,0.25,0.25,0.25,0.25,0.25,1.0,0.0,14600
3,133900,14800,14600,14550,0.684932,0.5,0.601,0.25,0.25,0.25,0.25,0.25,1.0,0.0,14700
4,511140,15550,14800,14750,3.061224,0.5,0.601,0.25,0.25,0.25,0.25,0.25,1.0,0.0,15150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
489,641524,9900,9160,9160,5.280172,3.5,3.534,2.00,2.00,2.00,2.00,2.00,4.5,2.5,9770
490,205243,9820,9770,9550,-0.307062,3.5,3.534,2.00,2.00,2.00,2.00,2.00,4.5,2.5,9740
491,398326,10180,9660,9660,3.080082,3.5,3.534,2.00,2.00,2.00,2.00,2.00,4.5,2.5,10040
492,196257,10150,10050,9850,-1.892430,3.5,3.534,2.00,2.00,2.00,2.00,2.00,4.5,2.5,9850
493,201361,10040,9960,9640,-1.522843,3.5,3.534,2.00,2.00,2.00,2.00,2.00,4.5,2.5,9700

## Model shells

In [ ]:
'''
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Dropout, LayerNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
from os.path import join
import tensorflow as tf


class Transformer2():
    def __init__(self, data, idx,day):
        self.data = data
        self.idx = idx
        self.time_steps = 60
        self.day=day

    def create_sequences(self, data):
        num_samples, num_features = data.shape
        sequences = []
        for i in range(num_samples - self.time_steps +1):
          sequences.append(data[i:i + self.time_steps, :])
        return np.array(sequences)

    def inverse_sequences(self,data_sequences):
        num_samples, num_steps, num_features = data_sequences.shape
        data = np.zeros((num_samples + self.time_steps - 1, num_features))
        for i in range(num_samples):
            data[i:i + self.time_steps, :] += data_sequences[i, :, :]
        data /= self.time_steps
        return data[:num_samples]
        #frquency domain inverse laplace transform

    def slicing_data(self):
        self.x_scaler = MinMaxScaler()
        self.y_scaler = MinMaxScaler()
        # Scaling features
        x_data = self.data[self.data.columns[:]]
        x_data = self.x_scaler.fit_transform(x_data)
        # Scaling target variable
        y_data = self.data[self.data.columns[:]]
        y_data = self.y_scaler.fit_transform(y_data)
        # validation set
        x_train_p, x_test, y_train_p, y_test = train_test_split(x_data, y_data, test_size=0.2, shuffle=False)
        x_train, x_val, y_train, y_val = train_test_split(x_train_p, y_train_p, test_size=0.25, shuffle=False)
        __t,x_final,__t,__t=train_test_split(x_data, y_data, test_size=60/len(y_data), shuffle=False)

        self.num_features = x_data.shape[1]
        self.num_samples=x_data.shape[0]

        self.x_train = self.create_sequences(x_train)
        self.x_test = self.create_sequences(x_test)
        self.x_val = self.create_sequences(x_val)
        self.x_final = self.create_sequences(x_final)

        self.y_train=self.create_sequences(y_train)
        self.y_test=self.create_sequences(y_test)
        self.y_val=self.create_sequences(y_val)


    def transformer_model(self):
        # Input layer
        inputs = Input(shape=(self.time_steps, self.num_features))

        # Transformer Encoder
        x = inputs
        for _ in range(4):  # Transformer Encoder Block의 반복 횟수 (하이퍼파라미터)
            x = self.transformer_encoder_block(x)

        # Output layer
        x = Dense(self.num_features, activation='relu')(x)

        model = Model(inputs, x, name="transformer_model")
        return model

    def transformer_encoder_block(self, inputs):
        # Multi-Head Self-Attention
        attention = tf.keras.layers.MultiHeadAttention(
            key_dim=self.num_features // 8, num_heads=8)(inputs, inputs)
        attention = Dropout(0.1)(attention)
        x = LayerNormalization(epsilon=1e-6)(inputs + attention)

        # Feed Forward Neural Network
        x = Dense(4 * self.num_features, activation="relu")(x)
        x = Dropout(0.1)(x)
        x = Dense(self.num_features, activation="relu")(x)
        x = LayerNormalization(epsilon=1e-6)(x + inputs)
        return x

    @tf.function(reduce_retracing=True)
    def train_model(self):
        model_save_path = '/content/drive/MyDrive/2023_1st_vac/KRX_modelings/best_model/Transformer2/{}/'.format(self.day)
        self.filename = join(model_save_path, 'checkpoint_{}_{}.ckpt'.format(self.day,self.idx))
        checkpoint = ModelCheckpoint(self.filename, save_weights_only=True, save_best_only=True, monitor='val_loss', verbose=0)
        earlystopping = EarlyStopping(monitor='val_loss', patience=100)
        model = self.transformer_model()
        model.compile(loss='mean_squared_error', optimizer=Adam(learning_rate=0.001))  # 학습률 (하이퍼파라미터)
        self.history = model.fit(self.x_train, self.y_train, epochs=1, batch_size=128, validation_data=(self.x_val, self.y_val), shuffle=False, callbacks=[checkpoint, earlystopping], verbose=0)

    def get_gap_by_test(self):
        self.model.load_weights(self.filename)
        pred = self.model.predict(self.x_test,verbose=0)
        rescaled_pred = self.y_scaler.inverse_transform(self.inverse_sequences(pred))
        rescaled_real = self.y_scaler.inverse_transform(self.inverse_sequences(self.y_test))

        gaps = []

        for p, r in zip(rescaled_pred, rescaled_real):
            gap = np.abs(p - r)
            gaps.append(gap)

        avg_gap = np.mean(gaps)

        return avg_gap

    def return_val(self):
        self.slicing_data()
        model = self.transformer_model()
        self.train_model()
        model.load_weights(self.filename)

        next_input_data = np.copy(self.x_final)
        for day in range(1, 16):
            pred_day = model.predict(np.expand_dims(next_input_data[-1], axis=0), verbose=0)
            next_input_data = np.concatenate((next_input_data, pred_day), axis=0)

        next_15_days_data = next_input_data[-15:]
        next_15_days_data = self.y_scaler.inverse_transform(self.inverse_sequences(next_15_days_data))

        columns = self.data.columns.tolist()
        ret_df = pd.DataFrame(next_15_days_data, columns=columns)

        prices = []
        for end_price in ret_df.iloc[:, -1]:
            prices.append(end_price)

        gap = self.get_gap_by_test()

        return prices, gap
'''
'''
하이퍼파라미터 추천:
-->  논문 이상치  instanced
Transformer Encoder Block의 반복 횟수: 4
Multi-Head Self-Attention에서 key_dim: 입력 특성 수의 1/8 크기로 추천 (예: num_features=100 이라면 key_dim=12)
학습률 (learning_rate): 0.001 (Adam optimizer를 사용하는 경우 일반적으로 사용되는 값)
Dropout 비율: 0.1 (적절한 정도의 regularization을 위한 값)
Transformer Encoder Block의 뉴런 수 (Dense layer의 뉴런 수): 입력 특성 수의 몇 배로 할지 지정 (예: 입력 특성 수가 100이면 4 * num_features=400 정도로 지정)
'''

'\n하이퍼파라미터 추천:\n-->  논문 이상치  instanced\nTransformer Encoder Block의 반복 횟수: 4\nMulti-Head Self-Attention에서 key_dim: 입력 특성 수의 1/8 크기로 추천 (예: num_features=100 이라면 key_dim=12)\n학습률 (learning_rate): 0.001 (Adam optimizer를 사용하는 경우 일반적으로 사용되는 값)\nDropout 비율: 0.1 (적절한 정도의 regularization을 위한 값)\nTransformer Encoder Block의 뉴런 수 (Dense layer의 뉴런 수): 입력 특성 수의 몇 배로 할지 지정 (예: 입력 특성 수가 100이면 4 * num_features=400 정도로 지정)\n'

## TEST **Shell**

## Predict **Shell**

In [ ]:
%pwd

'/content'

In [ ]:
%cd /content/drive/MyDrive/2023_1st_vac/KRX_modelings/Transformer_predict/src

/content/drive/MyDrive/2023_1st_vac/KRX_modelings/Transformer_predict/src

In [ ]:
from transformer_module import Transformer

In [ ]:
idx=0

pred_list=[]
gap_acc=[]
out_labels=[]

## #1

In [ ]:
for c in sliced_dataframes[0:500]:
  print(labels.iloc[idx])
  print("{}번째 종목코드".format(idx))
  trans_model=Transformer(data=c,idx=idx,day='230727_1')
  pred,gap = trans_model.return_val()
  sleep(1)
  pred_list.append(pred)
  gap_acc.append(gap)
  idx+=1
  #to prevent model corrupting

종목코드    A000020
Name: 502, dtype: object
0번째 종목코드
종목코드    A000040
Name: 118, dtype: object
1번째 종목코드
종목코드    A000050
Name: 243, dtype: object
2번째 종목코드
종목코드    A000070
Name: 760, dtype: object
3번째 종목코드
종목코드    A000080
Name: 1803, dtype: object
4번째 종목코드

WARNING:tensorflow:5 out of the last 9 calls to <function Model.make_train_function.<locals>.train_function at 0x7bcccff4bbe0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 5 calls to <function Model.make_test_function.<locals>.test_function at 0x7bcce05f9990> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

종목코드    A000100
Name: 1328, dtype: object
5번째 종목코드

WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_train_function.<locals>.train_function at 0x7bccfa98e050> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 6 calls to <function Model.make_test_function.<locals>.test_function at 0x7bcce040c790> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

종목코드    A000120
Name: 16, dtype: object
6번째 종목코드
종목코드    A000140
Name: 1804, dtype: object
7번째 종목코드
종목코드    A000150
Name: 503, dtype: object
8번째 종목코드
종목코드    A000180
Name: 840, dtype: object
9번째 종목코드
종목코드    A000210
Name: 33, dtype: object
10번째 종목코드
종목코드    A000220
Name: 1320, dtype: object
11번째 종목코드
종목코드    A000230
Name: 1412, dtype: object
12번째 종목코드
종목코드    A000240
Name: 1823, dtype: object
13번째 종목코드
종목코드    A000250
Name: 776, dtype: object
14번째 종목코드
종목코드    A000270
Name: 298, dtype: object
15번째 종목코드
종목코드    A000300
Name: 416, dtype: object
16번째 종목코드
종목코드    A000320
Name: 346, dtype: object
17번째 종목코드
종목코드    A000370
Name: 1903, dtype: object
18번째 종목코드
종목코드    A000390
Name: 787, dtype: object
19번째 종목코드
종목코드    A000400
Name: 569, dtype: object
20번째 종목코드
종목코드    A000430
Name: 407, dtype: object
21번째 종목코드
종목코드    A000440
Name: 1496, dtype: object
22번째 종목코드
종목코드    A000480
Name: 1481, dtype: object
23번째 종목코드
종목코드    A000490
Name: 376, dtype: object
24번째 종목코드
종목코드    A000500
Name: 228, dtype: object
25번째 종목코드
종목코드    A000520
Name: 770, dtype: object
26번째 종목코드
종목코드    A000540
Name: 1996, dtype: object
27번째 종목코드
종목코드    A000590
Name: 24, dtype: object
28번째 종목코드
종목코드    A000640
Name: 474, dtype: object
29번째 종목코드
종목코드    A000650
Name: 1528, dtype: object
30번째 종목코드
종목코드    A000660
Name: 200, dtype: object
31번째 종목코드
종목코드    A000670
Name: 1179, dtype: object
32번째 종목코드
종목코드    A000680
Name: 140, dtype: object
33번째 종목코드
종목코드    A000700
Name: 1314, dtype: object
34번째 종목코드
종목코드    A000720
Name: 1918, dtype: object
35번째 종목코드
종목코드    A000760
Name: 1381, dtype: object
36번째 종목코드
종목코드    A000810
Name: 752, dtype: object
37번째 종목코드
종목코드    A000850
Name: 1964, dtype: object
38번째 종목코드
종목코드    A000860
Name: 230, dtype: object
39번째 종목코드
종목코드    A000880
Name: 1901, dtype: object
40번째 종목코드
종목코드    A000890
Name: 687, dtype: object
41번째 종목코드
종목코드    A000910
Name: 1297, dtype: object
42번째 종목코드
종목코드    A000950
Name: 1436, dtype: object
43번째 종목코드
종목코드    A000970
Name: 1833, dtype: object
44번째 종목코드
종목코드    A000990
Name: 28, dtype: object
45번째 종목코드
종목코드    A001000
Name: 916, dtype: object
46번째 종목코드
종목코드    A001020
Name: 1729, dtype: object
47번째 종목코드
종목코드    A001040
Name: 12, dtype: object
48번째 종목코드
종목코드    A001060
Name: 90, dtype: object
49번째 종목코드
종목코드    A001070
Name: 427, dtype: object
50번째 종목코드
종목코드    A001080
Name: 595, dtype: object
51번째 종목코드
종목코드    A001120
Name: 143, dtype: object
52번째 종목코드
종목코드    A001130
Name: 433, dtype: object
53번째 종목코드
종목코드    A001140
Name: 272, dtype: object
54번째 종목코드
종목코드    A001200
Name: 1325, dtype: object
55번째 종목코드
종목코드    A001230
Name: 463, dtype: object
56번째 종목코드
종목코드    A001250
Name: 56, dtype: object
57번째 종목코드
종목코드    A001260
Name: 316, dtype: object
58번째 종목코드
종목코드    A001270
Name: 690, dtype: object
59번째 종목코드
종목코드    A001290
Name: 790, dtype: object
60번째 종목코드
종목코드    A001340
Name: 672, dtype: object
61번째 종목코드
종목코드    A001360
Name: 747, dtype: object
62번째 종목코드
종목코드    A001380
Name: 179, dtype: object
63번째 종목코드
종목코드    A001390
Name: 110, dtype: object
64번째 종목코드
종목코드    A001430
Name: 849, dtype: object
65번째 종목코드
종목코드    A001440
Name: 430, dtype: object
66번째 종목코드
종목코드    A001450
Name: 1944, dtype: object
67번째 종목코드
종목코드    A001460
Name: 10, dtype: object
68번째 종목코드
종목코드    A001470
Name: 737, dtype: object
69번째 종목코드
종목코드    A001500
Name: 1940, dtype: object
70번째 종목코드
종목코드    A001510
Name: 197, dtype: object
71번째 종목코드
종목코드    A001520
Name: 480, dtype: object
72번째 종목코드
종목코드    A001530
Name: 32, dtype: object
73번째 종목코드
종목코드    A001540
Name: 1027, dtype: object
74번째 종목코드
종목코드    A001550
Name: 1480, dtype: object
75번째 종목코드
종목코드    A001560
Name: 1465, dtype: object
76번째 종목코드
종목코드    A001570
Name: 289, dtype: object
77번째 종목코드
종목코드    A001620
Name: 1551, dtype: object
78번째 종목코드
종목코드    A001630
Name: 1489, dtype: object
79번째 종목코드
종목코드    A001680
Name: 387, dtype: object
80번째 종목코드
종목코드    A001720
Name: 929, dtype: object
81번째 종목코드
종목코드    A001740
Name: 188, dtype: object
82번째 종목코드
종목코드    A001750
Name: 1879, dtype: object
83번째 종목코드
종목코드    A001780
Name: 1031, dtype: object
84번째 종목코드
종목코드    A001790
Name: 432, dtype: object
85번째 종목코드
종목코드    A001800
Name: 1198, dtype: object
86번째 종목코드
종목코드    A001810
Name: 635, dtype: object
87번째 종목코드
종목코드    A001820
Name: 786, dtype: object
88번째 종목코드
종목코드    A001840
Name: 1380, dtype: object
89번째 종목코드
종목코드    A001880
Name: 34, dtype: object
90번째 종목코드
종목코드    A001940
Name: 113, dtype: object
91번째 종목코드
종목코드    A002020
Name: 1604, dtype: object
92번째 종목코드
종목코드    A002030
Name: 986, dtype: object
93번째 종목코드
종목코드    A002100
Name: 238, dtype: object
94번째 종목코드
종목코드    A002140
Name: 249, dtype: object
95번째 종목코드
종목코드    A002150
Name: 458, dtype: object
96번째 종목코드
종목코드    A002170
Name: 758, dtype: object
97번째 종목코드
종목코드    A002200
Name: 1820, dtype: object
98번째 종목코드
종목코드    A002210
Name: 470, dtype: object
99번째 종목코드
종목코드    A002220
Name: 1886, dtype: object
100번째 종목코드
종목코드    A002230
Name: 1771, dtype: object
101번째 종목코드
종목코드    A002240
Name: 253, dtype: object
102번째 종목코드
종목코드    A002290
Name: 768, dtype: object
103번째 종목코드
종목코드    A002310
Name: 988, dtype: object
104번째 종목코드
종목코드    A002320
Name: 1893, dtype: object
105번째 종목코드
종목코드    A002350
Name: 338, dtype: object
106번째 종목코드
종목코드    A002360
Name: 181, dtype: object
107번째 종목코드
종목코드    A002380
Name: 97, dtype: object
108번째 종목코드
종목코드    A002390
Name: 1853, dtype: object
109번째 종목코드
종목코드    A002410
Name: 677, dtype: object
110번째 종목코드
종목코드    A002450
Name: 767, dtype: object
111번째 종목코드
종목코드    A002460
Name: 1954, dtype: object
112번째 종목코드
종목코드    A002600
Name: 1486, dtype: object
113번째 종목코드
종목코드    A002620
Name: 1468, dtype: object
114번째 종목코드
종목코드    A002630
Name: 1196, dtype: object
115번째 종목코드
종목코드    A002680
Name: 1900, dtype: object
116번째 종목코드
종목코드    A002690
Name: 499, dtype: object
117번째 종목코드
종목코드    A002700
Name: 932, dtype: object
118번째 종목코드
종목코드    A002710
Name: 212, dtype: object
119번째 종목코드
종목코드    A002720
Name: 278, dtype: object
120번째 종목코드
종목코드    A002760
Name: 684, dtype: object
121번째 종목코드
종목코드    A002780
Name: 1523, dtype: object
122번째 종목코드
종목코드    A002790
Name: 978, dtype: object
123번째 종목코드
종목코드    A002800
Name: 927, dtype: object
124번째 종목코드
종목코드    A002810
Name: 762, dtype: object
125번째 종목코드
종목코드    A002840
Name: 649, dtype: object
126번째 종목코드
종목코드    A002880
Name: 414, dtype: object
127번째 종목코드
종목코드    A002900
Name: 220, dtype: object
128번째 종목코드
종목코드    A002920
Name: 1312, dtype: object
129번째 종목코드
종목코드    A002960
Name: 1821, dtype: object
130번째 종목코드
종목코드    A002990
Name: 290, dtype: object
131번째 종목코드
종목코드    A003000
Name: 689, dtype: object
132번째 종목코드
종목코드    A003010
Name: 1948, dtype: object
133번째 종목코드
종목코드    A003030
Name: 851, dtype: object
134번째 종목코드
종목코드    A003060
Name: 1119, dtype: object
135번째 종목코드
종목코드    A003070
Name: 1605, dtype: object
136번째 종목코드
종목코드    A003080
Name: 834, dtype: object
137번째 종목코드
종목코드    A003090
Name: 404, dtype: object
138번째 종목코드
종목코드    A003100
Name: 825, dtype: object
139번째 종목코드
종목코드    A003120
Name: 1414, dtype: object
140번째 종목코드
종목코드    A003160
Name: 518, dtype: object
141번째 종목코드
종목코드    A003200
Name: 1417, dtype: object
142번째 종목코드
종목코드    A003220
Name: 411, dtype: object
143번째 종목코드
종목코드    A003230
Name: 756, dtype: object
144번째 종목코드
종목코드    A003240
Name: 1653, dtype: object
145번째 종목코드
종목코드    A003280
Name: 1997, dtype: object
146번째 종목코드
종목코드    A003300
Name: 1888, dtype: object
147번째 종목코드
종목코드    A003310
Name: 418, dtype: object
148번째 종목코드
종목코드    A003350
Name: 1849, dtype: object
149번째 종목코드
종목코드    A003380
Name: 1792, dtype: object
150번째 종목코드
종목코드    A003410
Name: 948, dtype: object
151번째 종목코드
종목코드    A003460
Name: 1329, dtype: object
152번째 종목코드
종목코드    A003470
Name: 1317, dtype: object
153번째 종목코드
종목코드    A003480
Name: 1894, dtype: object
154번째 종목코드
종목코드    A003490
Name: 434, dtype: object
155번째 종목코드
종목코드    A003520
Name: 1178, dtype: object
156번째 종목코드
종목코드    A003530
Name: 1907, dtype: object
157번째 종목코드
종목코드    A003540
Name: 395, dtype: object
158번째 종목코드
종목코드    A003550
Name: 129, dtype: object
159번째 종목코드
종목코드    A003560
Name: 84, dtype: object
160번째 종목코드
종목코드    A003570
Name: 203, dtype: object
161번째 종목코드
종목코드    A003580
Name: 73, dtype: object
162번째 종목코드
종목코드    A003610
Name: 670, dtype: object
163번째 종목코드
종목코드    A003620
Name: 107, dtype: object
164번째 종목코드
종목코드    A003650
Name: 653, dtype: object
165번째 종목코드
종목코드    A003670
Name: 1738, dtype: object
166번째 종목코드
종목코드    A003690
Name: 1584, dtype: object
167번째 종목코드
종목코드    A003720
Name: 761, dtype: object
168번째 종목코드
종목코드    A003780
Name: 1516, dtype: object
169번째 종목코드
종목코드    A003800
Name: 1101, dtype: object
170번째 종목코드
종목코드    A003830
Name: 436, dtype: object
171번째 종목코드
종목코드    A003850
Name: 685, dtype: object
172번째 종목코드
종목코드    A003920
Name: 319, dtype: object
173번째 종목코드
종목코드    A003960
Name: 726, dtype: object
174번째 종목코드
종목코드    A004000
Name: 573, dtype: object
175번째 종목코드
종목코드    A004020
Name: 1937, dtype: object
176번째 종목코드
종목코드    A004060
Name: 180, dtype: object
177번째 종목코드
종목코드    A004080
Name: 940, dtype: object
178번째 종목코드
종목코드    A004090
Name: 1818, dtype: object
179번째 종목코드
종목코드    A004100
Name: 1657, dtype: object
180번째 종목코드
종목코드    A004140
Name: 466, dtype: object
181번째 종목코드
종목코드    A004150
Name: 1871, dtype: object
182번째 종목코드
종목코드    A004170
Name: 921, dtype: object
183번째 종목코드
종목코드    A004250
Name: 158, dtype: object
184번째 종목코드
종목코드    A004270
Name: 318, dtype: object
185번째 종목코드
종목코드    A004310
Name: 1930, dtype: object
186번째 종목코드
종목코드    A004360
Name: 846, dtype: object
187번째 종목코드
종목코드    A004370
Name: 354, dtype: object
188번째 종목코드
종목코드    A004380
Name: 766, dtype: object
189번째 종목코드
종목코드    A004410
Name: 811, dtype: object
190번째 종목코드
종목코드    A004430
Name: 886, dtype: object
191번째 종목코드
종목코드    A004440
Name: 769, dtype: object
192번째 종목코드
종목코드    A004450
Name: 783, dtype: object
193번째 종목코드
종목코드    A004490
Name: 847, dtype: object
194번째 종목코드
종목코드    A004540
Name: 302, dtype: object
195번째 종목코드
종목코드    A004560
Name: 1929, dtype: object
196번째 종목코드
종목코드    A004590
Name: 1807, dtype: object
197번째 종목코드
종목코드    A004650
Name: 1526, dtype: object
198번째 종목코드
종목코드    A004690
Name: 777, dtype: object
199번째 종목코드
종목코드    A004700
Name: 1479, dtype: object
200번째 종목코드
종목코드    A004710
Name: 1870, dtype: object
201번째 종목코드
종목코드    A004720
Name: 1721, dtype: object
202번째 종목코드
종목코드    A004770
Name: 950, dtype: object
203번째 종목코드
종목코드    A004780
Name: 379, dtype: object
204번째 종목코드
종목코드    A004800
Name: 1967, dtype: object
205번째 종목코드
종목코드    A004830
Name: 448, dtype: object
206번째 종목코드
종목코드    A004840
Name: 38, dtype: object
207번째 종목코드
종목코드    A004870
Name: 1695, dtype: object
208번째 종목코드
종목코드    A004890
Name: 498, dtype: object
209번째 종목코드
종목코드    A004910
Name: 1478, dtype: object
210번째 종목코드
종목코드    A004920
Name: 959, dtype: object
211번째 종목코드
종목코드    A004960
Name: 1875, dtype: object
212번째 종목코드
종목코드    A004970
Name: 915, dtype: object
213번째 종목코드
종목코드    A004980
Name: 835, dtype: object
214번째 종목코드
종목코드    A004990
Name: 575, dtype: object
215번째 종목코드
종목코드    A005010
Name: 1988, dtype: object
216번째 종목코드
종목코드    A005070
Name: 1596, dtype: object
217번째 종목코드
종목코드    A005090
Name: 177, dtype: object
218번째 종목코드
종목코드    A005110
Name: 1896, dtype: object
219번째 종목코드
종목코드    A005160
Name: 461, dtype: object
220번째 종목코드
종목코드    A005180
Name: 724, dtype: object
221번째 종목코드
종목코드    A005250
Name: 352, dtype: object
222번째 종목코드
종목코드    A005290
Name: 500, dtype: object
223번째 종목코드
종목코드    A005300
Name: 576, dtype: object
224번째 종목코드
종목코드    A005320
Name: 271, dtype: object
225번째 종목코드
종목코드    A005360
Name: 622, dtype: object
226번째 종목코드
종목코드    A005380
Name: 1939, dtype: object
227번째 종목코드
종목코드    A005390
Name: 920, dtype: object
228번째 종목코드
종목코드    A005420
Name: 1597, dtype: object
229번째 종목코드
종목코드    A005430
Name: 1810, dtype: object
230번째 종목코드
종목코드    A005440
Name: 1938, dtype: object
231번째 종목코드
종목코드    A005490
Name: 162, dtype: object
232번째 종목코드

KeyboardInterrupt: ignored

In [ ]:
len(pred_list)

232

In [ ]:
pred_csv_df=pd.DataFrame(
    {
    '종가':pred_list,
    'gap':gap_acc
    },
    index=[i for i in range(232)],
    columns=['종가','gap']
)

In [ ]:
pred_csv_df.to_csv('/content/drive/MyDrive/2023_1st_vac/KRX_modelings/predicitions/{}.csv'.format("230725_v0.1"),index=True)

## #2

In [ ]:
idx=232

In [ ]:
for c in sliced_dataframes[idx:2*idx]:
  print(labels.iloc[idx])
  print("{}번째 종목코드".format(idx))
  trans_model=Transformer(data=c,idx=idx,day='230727_1')
  pred,gap = trans_model.return_val()
  sleep(1)
  pred_list.append(pred)
  gap_acc.append(gap)
  idx+=1
  #to prevent model corrupting

종목코드    A005490
Name: 162, dtype: object
232번째 종목코드
종목코드    A005500
Name: 775, dtype: object
233번째 종목코드
종목코드    A005610
Name: 207, dtype: object
234번째 종목코드
종목코드    A005670
Name: 1746, dtype: object
235번째 종목코드
종목코드    A005680
Name: 764, dtype: object
236번째 종목코드

WARNING:tensorflow:5 out of the last 9 calls to <function Model.make_train_function.<locals>.train_function at 0x7f50707655a0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 5 calls to <function Model.make_test_function.<locals>.test_function at 0x7f509843fc70> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

종목코드    A005690
Name: 1704, dtype: object
237번째 종목코드

WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_train_function.<locals>.train_function at 0x7f51107684c0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 6 calls to <function Model.make_test_function.<locals>.test_function at 0x7f51221de5f0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

종목코드    A005710
Name: 409, dtype: object
238번째 종목코드
종목코드    A005720
Name: 337, dtype: object
239번째 종목코드
종목코드    A005740
Name: 1633, dtype: object
240번째 종목코드
종목코드    A005750
Name: 380, dtype: object
241번째 종목코드
종목코드    A005800
Name: 928, dtype: object
242번째 종목코드
종목코드    A005810
Name: 1752, dtype: object
243번째 종목코드
종목코드    A005820
Name: 1256, dtype: object
244번째 종목코드
종목코드    A005830
Name: 27, dtype: object
245번째 종목코드
종목코드    A005850
Name: 1075, dtype: object
246번째 종목코드
종목코드    A005860
Name: 1884, dtype: object
247번째 종목코드
종목코드    A005870
Name: 1976, dtype: object
248번째 종목코드
종목코드    A005880
Name: 435, dtype: object
249번째 종목코드
종목코드    A005930
Name: 746, dtype: object
250번째 종목코드
종목코드    A005940
Name: 154, dtype: object
251번째 종목코드
종목코드    A005950
Name: 1358, dtype: object
252번째 종목코드
종목코드    A005960
Name: 468, dtype: object
253번째 종목코드
종목코드    A005990
Name: 597, dtype: object
254번째 종목코드
종목코드    A006040
Name: 493, dtype: object
255번째 종목코드
종목코드    A006050
Name: 275, dtype: object
256번째 종목코드
종목코드    A006060
Name: 1957, dtype: object
257번째 종목코드
종목코드    A006090
Name: 730, dtype: object
258번째 종목코드
종목코드    A006110
Name: 753, dtype: object
259번째 종목코드
종목코드    A006120
Name: 189, dtype: object
260번째 종목코드
종목코드    A006140
Name: 1779, dtype: object
261번째 종목코드
종목코드    A006200
Name: 1829, dtype: object
262번째 종목코드
종목코드    A006220
Name: 1471, dtype: object
263번째 종목코드
종목코드    A006260
Name: 138, dtype: object
264번째 종목코드
종목코드    A006280
Name: 349, dtype: object
265번째 종목코드
종목코드    A006340
Name: 410, dtype: object
266번째 종목코드
종목코드    A006360
Name: 55, dtype: object
267번째 종목코드
종목코드    A006370
Name: 373, dtype: object
268번째 종목코드
종목코드    A006390
Name: 1887, dtype: object
269번째 종목코드
종목코드    A006400
Name: 738, dtype: object
270번째 종목코드
종목코드    A006490
Name: 1390, dtype: object
271번째 종목코드
종목코드    A006570
Name: 382, dtype: object
272번째 종목코드
종목코드    A006580
Name: 399, dtype: object
273번째 종목코드
종목코드    A006620
Name: 459, dtype: object
274번째 종목코드
종목코드    A006650
Name: 429, dtype: object
275번째 종목코드
종목코드    A006660
Name: 739, dtype: object
276번째 종목코드
종목코드    A006730
Name: 803, dtype: object
277번째 종목코드
종목코드    A006740
Name: 1181, dtype: object
278번째 종목코드
종목코드    A006800
Name: 646, dtype: object
279번째 종목코드
종목코드    A006840
Name: 2, dtype: object
280번째 종목코드
종목코드    A006880
Name: 926, dtype: object
281번째 종목코드
종목코드    A006890
Name: 1651, dtype: object
282번째 종목코드
종목코드    A006910
Name: 686, dtype: object
283번째 종목코드
종목코드    A006980
Name: 1245, dtype: object
284번째 종목코드
종목코드    A007070
Name: 57, dtype: object
285번째 종목코드
종목코드    A007110
Name: 1418, dtype: object
286번째 종목코드
종목코드    A007120
Name: 643, dtype: object
287번째 종목코드
종목코드    A007160
Name: 728, dtype: object
288번째 종목코드
종목코드    A007210
Name: 681, dtype: object
289번째 종목코드
종목코드    A007280
Name: 1844, dtype: object
290번째 종목코드
종목코드    A007310
Name: 1191, dtype: object
291번째 종목코드
종목코드    A007330
Name: 1748, dtype: object
292번째 종목코드
종목코드    A007340
Name: 37, dtype: object
293번째 종목코드
종목코드    A007370
Name: 1517, dtype: object
294번째 종목코드
종목코드    A007390
Name: 334, dtype: object
295번째 종목코드
종목코드    A007460
Name: 1117, dtype: object
296번째 종목코드
종목코드    A007530
Name: 1224, dtype: object
297번째 종목코드
종목코드    A007540
Name: 799, dtype: object
298번째 종목코드
종목코드    A007570
Name: 1419, dtype: object
299번째 종목코드
종목코드    A007590
Name: 467, dtype: object
300번째 종목코드
종목코드    A007610
Name: 826, dtype: object
301번째 종목코드
종목코드    A007660
Name: 1357, dtype: object
302번째 종목코드
종목코드    A007680
Name: 406, dtype: object
303번째 종목코드
종목코드    A007690
Name: 270, dtype: object
304번째 종목코드
종목코드    A007700
Name: 49, dtype: object
305번째 종목코드
종목코드    A007720
Name: 383, dtype: object
306번째 종목코드
종목코드    A007770
Name: 1889, dtype: object
307번째 종목코드
종목코드    A007810
Name: 1581, dtype: object
308번째 종목코드
종목코드    A007820
Name: 1078, dtype: object
309번째 종목코드
종목코드    A007860
Name: 805, dtype: object
310번째 종목코드
종목코드    A007980
Name: 1661, dtype: object
311번째 종목코드
종목코드    A008040
Name: 727, dtype: object
312번째 종목코드
종목코드    A008060
Name: 374, dtype: object
313번째 종목코드
종목코드    A008110
Name: 378, dtype: object
314번째 종목코드
종목코드    A008250
Name: 1332, dtype: object
315번째 종목코드
종목코드    A008260
Name: 157, dtype: object
316번째 종목코드
종목코드    A008350
Name: 317, dtype: object
317번째 종목코드
종목코드    A008370
Name: 1267, dtype: object
318번째 종목코드
종목코드    A008420
Name: 638, dtype: object
319번째 종목코드
종목코드    A008490
Name: 822, dtype: object
320번째 종목코드
종목코드    A008700
Name: 976, dtype: object
321번째 종목코드
종목코드    A008730
Name: 1330, dtype: object
322번째 종목코드
종목코드    A008770
Name: 1950, dtype: object
323번째 종목코드
종목코드    A008830
Name: 377, dtype: object
324번째 종목코드
종목코드    A008870
Name: 288, dtype: object
325번째 종목코드
종목코드    A008930
Name: 1858, dtype: object
326번째 종목코드
종목코드    A008970
Name: 485, dtype: object
327번째 종목코드
종목코드    A009070
Name: 101, dtype: object
328번째 종목코드
종목코드    A009150
Name: 745, dtype: object
329번째 종목코드
종목코드    A009160
Name: 182, dtype: object
330번째 종목코드
종목코드    A009180
Name: 1866, dtype: object
331번째 종목코드
종목코드    A009190
Name: 397, dtype: object
332번째 종목코드
종목코드    A009200
Name: 636, dtype: object
333번째 종목코드
종목코드    A009240
Name: 1861, dtype: object
334번째 종목코드
종목코드    A009270
Name: 930, dtype: object
335번째 종목코드
종목코드    A009290
Name: 261, dtype: object
336번째 종목코드
종목코드    A009300
Name: 754, dtype: object
337번째 종목코드
종목코드    A009320
Name: 402, dtype: object
338번째 종목코드
종목코드    A009410
Name: 1658, dtype: object
339번째 종목코드
종목코드    A009420
Name: 1881, dtype: object
340번째 종목코드
종목코드    A009440
Name: 102, dtype: object
341번째 종목코드
종목코드    A009450
Name: 239, dtype: object
342번째 종목코드
종목코드    A009460
Name: 1898, dtype: object
343번째 종목코드
종목코드    A009470
Name: 784, dtype: object
344번째 종목코드
종목코드    A009520
Name: 1736, dtype: object
345번째 종목코드
종목코드    A009540
Name: 64, dtype: object
346번째 종목코드
종목코드    A009580
Name: 634, dtype: object
347번째 종목코드
종목코드    A009620
Name: 735, dtype: object
348번째 종목코드
종목코드    A009680
Name: 632, dtype: object
349번째 종목코드
종목코드    A009730
Name: 1590, dtype: object
350번째 종목코드
종목코드    A009770
Name: 771, dtype: object
351번째 종목코드
종목코드    A009780
Name: 1165, dtype: object
352번째 종목코드
종목코드    A009810
Name: 1762, dtype: object
353번째 종목코드
종목코드    A009830
Name: 1904, dtype: object
354번째 종목코드
종목코드    A009900
Name: 620, dtype: object
355번째 종목코드
종목코드    A009970
Name: 1177, dtype: object
356번째 종목코드
종목코드    A010040
Name: 1813, dtype: object
357번째 종목코드
종목코드    A010050
Name: 1243, dtype: object
358번째 종목코드
종목코드    A010060
Name: 159, dtype: object
359번째 종목코드
종목코드    A010100
Name: 1816, dtype: object
360번째 종목코드
종목코드    A010120
Name: 139, dtype: object
361번째 종목코드
종목코드    A010130
Name: 252, dtype: object
362번째 종목코드
종목코드    A010140
Name: 748, dtype: object
363번째 종목코드
종목코드    A010170
Name: 425, dtype: object
364번째 종목코드
종목코드    A010240
Name: 1994, dtype: object
365번째 종목코드
종목코드    A010280
Name: 949, dtype: object
366번째 종목코드
종목코드    A010470
Name: 1199, dtype: object
367번째 종목코드
종목코드    A010580
Name: 1077, dtype: object
368번째 종목코드
종목코드    A010600
Name: 1272, dtype: object
369번째 종목코드
종목코드    A010620
Name: 1925, dtype: object
370번째 종목코드
종목코드    A010640
Name: 1518, dtype: object
371번째 종목코드
종목코드    A010660
Name: 1963, dtype: object
372번째 종목코드
종목코드    A010690
Name: 1959, dtype: object
373번째 종목코드
종목코드    A010770
Name: 1732, dtype: object
374번째 종목코드
종목코드    A010780
Name: 1006, dtype: object
375번째 종목코드
종목코드    A010820
Name: 1725, dtype: object
376번째 종목코드
종목코드    A010950
Name: 166, dtype: object
377번째 종목코드
종목코드    A010960
Name: 781, dtype: object
378번째 종목코드
종목코드    A011000
Name: 1522, dtype: object
379번째 종목코드
종목코드    A011040
Name: 242, dtype: object
380번째 종목코드
종목코드    A011070
Name: 133, dtype: object
381번째 종목코드
종목코드    A011150
Name: 17, dtype: object
382번째 종목코드
종목코드    A011170
Name: 577, dtype: object
383번째 종목코드
종목코드    A011200
Name: 81, dtype: object
384번째 종목코드
종목코드    A011210
Name: 1935, dtype: object
385번째 종목코드
종목코드    A011230
Name: 785, dtype: object
386번째 종목코드
종목코드    A011280
Name: 1654, dtype: object
387번째 종목코드
종목코드    A011300
Name: 836, dtype: object
388번째 종목코드
종목코드    A011320
Name: 1302, dtype: object
389번째 종목코드
종목코드    A011330
Name: 1300, dtype: object
390번째 종목코드
종목코드    A011370
Name: 820, dtype: object
391번째 종목코드
종목코드    A011390
Name: 693, dtype: object
392번째 종목코드
종목코드    A011420
Name: 235, dtype: object
393번째 종목코드
종목코드    A011500
Name: 1852, dtype: object
394번째 종목코드
종목코드    A011560
Name: 848, dtype: object
395번째 종목코드
종목코드    A011690
Name: 1231, dtype: object
396번째 종목코드
종목코드    A011700
Name: 1876, dtype: object
397번째 종목코드
종목코드    A011760
Name: 1941, dtype: object
398번째 종목코드
종목코드    A011780
Name: 291, dtype: object
399번째 종목코드
종목코드    A011790
Name: 186, dtype: object
400번째 종목코드
종목코드    A011810
Name: 208, dtype: object
401번째 종목코드
종목코드    A011930
Name: 919, dtype: object
402번째 종목코드
종목코드    A012030
Name: 25, dtype: object
403번째 종목코드
종목코드    A012160
Name: 1184, dtype: object
404번째 종목코드
종목코드    A012170
Name: 990, dtype: object
405번째 종목코드
종목코드    A012200
Name: 248, dtype: object
406번째 종목코드
종목코드    A012280
Name: 1182, dtype: object
407번째 종목코드
종목코드    A012320
Name: 241, dtype: object
408번째 종목코드
종목코드    A012330
Name: 1923, dtype: object
409번째 종목코드
종목코드    A012340
Name: 359, dtype: object
410번째 종목코드
종목코드    A012450
Name: 1906, dtype: object
411번째 종목코드
종목코드    A012510
Name: 444, dtype: object
412번째 종목코드
종목코드    A012600
Name: 1529, dtype: object
413번째 종목코드
종목코드    A012610
Name: 245, dtype: object
414번째 종목코드
종목코드    A012630
Name: 60, dtype: object
415번째 종목코드
종목코드    A012690
Name: 621, dtype: object
416번째 종목코드
종목코드    A012700
Name: 585, dtype: object
417번째 종목코드
종목코드    A012750
Name: 1080, dtype: object
418번째 종목코드
종목코드    A012790
Name: 933, dtype: object
419번째 종목코드
종목코드    A012800
Name: 420, dtype: object
420번째 종목코드
종목코드    A012860
Name: 627, dtype: object
421번째 종목코드
종목코드    A013030
Name: 1796, dtype: object
422번째 종목코드
종목코드    A013120
Name: 491, dtype: object
423번째 종목코드
종목코드    A013310
Name: 1023, dtype: object
424번째 종목코드
종목코드    A013360
Name: 1413, dtype: object
425번째 종목코드
종목코드    A013520
Name: 1958, dtype: object
426번째 종목코드
종목코드    A013570
Name: 531, dtype: object
427번째 종목코드
종목코드    A013580
Name: 247, dtype: object
428번째 종목코드
종목코드    A013700
Name: 300, dtype: object
429번째 종목코드
종목코드    A013720
Name: 11, dtype: object
430번째 종목코드
종목코드    A013810
Name: 902, dtype: object
431번째 종목코드
종목코드    A013870
Name: 1508, dtype: object
432번째 종목코드
종목코드    A013890
Name: 1499, dtype: object
433번째 종목코드
종목코드    A013990
Name: 973, dtype: object
434번째 종목코드
종목코드    A014130
Name: 1882, dtype: object
435번째 종목코드
종목코드    A014160
Name: 400, dtype: object
436번째 종목코드
종목코드    A014190
Name: 1263, dtype: object
437번째 종목코드
종목코드    A014200
Name: 262, dtype: object
438번째 종목코드
종목코드    A014280
Name: 286, dtype: object
439번째 종목코드
종목코드    A014440
Name: 1174, dtype: object
440번째 종목코드
종목코드    A014470
Name: 692, dtype: object
441번째 종목코드
종목코드    A014530
Name: 283, dtype: object
442번째 종목코드
종목코드    A014570
Name: 254, dtype: object
443번째 종목코드
종목코드    A014580
Name: 1649, dtype: object
444번째 종목코드
종목코드    A014620
Name: 831, dtype: object
445번째 종목코드
종목코드    A014680
Name: 1869, dtype: object
446번째 종목코드
종목코드    A014710
Name: 729, dtype: object
447번째 종목코드
종목코드    A014790
Name: 71, dtype: object
448번째 종목코드
종목코드    A014820
Name: 494, dtype: object
449번째 종목코드
종목코드    A014830
Name: 1294, dtype: object
450번째 종목코드
종목코드    A014910
Name: 833, dtype: object
451번째 종목코드
종목코드    A014940
Name: 1195, dtype: object
452번째 종목코드
종목코드    A014970
Name: 732, dtype: object
453번째 종목코드
종목코드    A014990
Name: 1383, dtype: object
454번째 종목코드
종목코드    A015230
Name: 421, dtype: object
455번째 종목코드
종목코드    A015260
Name: 1105, dtype: object
456번째 종목코드
종목코드    A015360
Name: 1187, dtype: object
457번째 종목코드
종목코드    A015540
Name: 955, dtype: object
458번째 종목코드
종목코드    A015590
Name: 1625, dtype: object
459번째 종목코드
종목코드    A015710
Name: 1614, dtype: object
460번째 종목코드
종목코드    A015750
Name: 839, dtype: object
461번째 종목코드
종목코드    A015760
Name: 1826, dtype: object
462번째 종목코드
종목코드    A015860
Name: 1426, dtype: object
463번째 종목코드

In [ ]:
pred_csv_df=pd.DataFrame(
    {
    '종가':pred_list,
    'gap':gap_acc
    },
    index=[i for i in range(232)],
    columns=['종가','gap']
)

In [ ]:
pred_csv_df.to_csv('/content/drive/MyDrive/2023_1st_vac/KRX_modelings/predicitions/{}.csv'.format("230725_v0.2"),index=True)

## #3

In [ ]:
idx=464

In [ ]:
for c in sliced_dataframes[idx:idx+262]:
  print(labels.iloc[idx])
  print("{}번째 종목코드".format(idx))
  trans_model=Transformer(data=c,idx=idx,day='230727_1')
  pred,gap = trans_model.return_val()
  sleep(1)
  pred_list.append(pred)
  gap_acc.append(gap)
  idx+=1
  #to prevent model corrupting
pred_csv_df=pd.DataFrame(
  {
  '종가':pred_list,
  'gap':gap_acc
  },
  index=[i for i in range(232)],
  columns=['종가','gap']
)
pred_csv_df.to_csv('/content/drive/MyDrive/2023_1st_vac/KRX_modelings/predicitions/{}.csv'.format("230725_v0.3"),index=True)

종목코드    A015890
Name: 1650, dtype: object
464번째 종목코드
종목코드    A016090
Name: 437, dtype: object
465번째 종목코드
종목코드    A016100
Name: 584, dtype: object
466번째 종목코드
종목코드    A016250
Name: 178, dtype: object
467번째 종목코드
종목코드    A016360
Name: 749, dtype: object
468번째 종목코드

WARNING:tensorflow:5 out of the last 9 calls to <function Model.make_train_function.<locals>.train_function at 0x7a182027beb0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 5 calls to <function Model.make_test_function.<locals>.test_function at 0x7a17ac3eb010> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

종목코드    A016380
Name: 108, dtype: object
469번째 종목코드

WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_train_function.<locals>.train_function at 0x7a182c09b370> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 6 calls to <function Model.make_test_function.<locals>.test_function at 0x7a17984ef010> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

종목코드    A016450
Name: 1865, dtype: object
470번째 종목코드
종목코드    A016580
Name: 1965, dtype: object
471번째 종목코드
종목코드    A016590
Name: 912, dtype: object
472번째 종목코드
종목코드    A016600
Name: 1631, dtype: object
473번째 종목코드
종목코드    A016610
Name: 26, dtype: object
474번째 종목코드
종목코드    A016710
Name: 394, dtype: object
475번째 종목코드
종목코드    A016740
Name: 508, dtype: object
476번째 종목코드
종목코드    A016790
Name: 1535, dtype: object
477번째 종목코드
종목코드    A016800
Name: 1726, dtype: object
478번째 종목코드
종목코드    A016880
Name: 1254, dtype: object
479번째 종목코드
종목코드    A017000
Name: 931, dtype: object
480번째 종목코드
종목코드    A017040
Name: 263, dtype: object
481번째 종목코드
종목코드    A017180
Name: 618, dtype: object
482번째 종목코드
종목코드    A017370
Name: 1247, dtype: object
483번째 종목코드
종목코드    A017390
Name: 808, dtype: object
484번째 종목코드
종목코드    A017480
Name: 780, dtype: object
485번째 종목코드
종목코드    A017510
Name: 845, dtype: object
486번째 종목코드
종목코드    A017550
Name: 889, dtype: object
487번째 종목코드
종목코드    A017650
Name: 381, dtype: object
488번째 종목코드
종목코드    A017670
Name: 199, dtype: object
489번째 종목코드
종목코드    A017800
Name: 1933, dtype: object
490번째 종목코드
종목코드    A017810
Name: 1749, dtype: object
491번째 종목코드
종목코드    A017890
Name: 1822, dtype: object
492번째 종목코드
종목코드    A017900
Name: 265, dtype: object
493번째 종목코드
종목코드    A017940
Name: 44, dtype: object
494번째 종목코드
종목코드    A017960
Name: 1835, dtype: object
495번째 종목코드
종목코드    A018000
Name: 1296, dtype: object
496번째 종목코드
종목코드    A018120
Name: 1512, dtype: object
497번째 종목코드
종목코드    A018250
Name: 1045, dtype: object
498번째 종목코드
종목코드    A018260
Name: 743, dtype: object
499번째 종목코드
종목코드    A018290
Name: 700, dtype: object
500번째 종목코드
종목코드    A018310
Name: 733, dtype: object
501번째 종목코드
종목코드    A018470
Name: 1485, dtype: object
502번째 종목코드
종목코드    A018500
Name: 492, dtype: object
503번째 종목코드
종목코드    A018620
Name: 1252, dtype: object
504번째 종목코드
종목코드    A018670
Name: 187, dtype: object
505번째 종목코드
종목코드    A018680
Name: 813, dtype: object
506번째 종목코드
종목코드    A018700
Name: 658, dtype: object
507번째 종목코드
종목코드    A018880
Name: 1880, dtype: object
508번째 종목코드
종목코드    A019010
Name: 679, dtype: object
509번째 종목코드
종목코드    A019170
Name: 936, dtype: object
510번째 종목코드
종목코드    A019180
Name: 1689, dtype: object
511번째 종목코드
종목코드    A019210
Name: 1229, dtype: object
512번째 종목코드
종목코드    A019440
Name: 852, dtype: object
513번째 종목코드
종목코드    A019540
Name: 1421, dtype: object
514번째 종목코드
종목코드    A019550
Name: 167, dtype: object
515번째 종목코드
종목코드    A019570
Name: 583, dtype: object
516번째 종목코드
종목코드    A019590
Name: 1161, dtype: object
517번째 종목코드
종목코드    A019660
Name: 285, dtype: object
518번째 종목코드
종목코드    A019680
Name: 372, dtype: object
519번째 종목코드
종목코드    A019770
Name: 807, dtype: object
520번째 종목코드
종목코드    A019990
Name: 1061, dtype: object
521번째 종목코드
종목코드    A020000
Name: 1862, dtype: object
522번째 종목코드
종목코드    A020120
Name: 1643, dtype: object
523번째 종목코드
종목코드    A020150
Name: 571, dtype: object
524번째 종목코드
종목코드    A020560
Name: 995, dtype: object
525번째 종목코드
종목코드    A020710
Name: 904, dtype: object
526번째 종목코드
종목코드    A020760
Name: 1423, dtype: object
527번째 종목코드
종목코드    A021050
Name: 814, dtype: object
528번째 종목코드
종목코드    A021080
Name: 1114, dtype: object
529번째 종목코드
종목코드    A021240
Name: 1609, dtype: object
530번째 종목코드
종목코드    A021320
Name: 98, dtype: object
531번째 종목코드
종목코드    A021650
Name: 1840, dtype: object
532번째 종목코드
종목코드    A021820
Name: 857, dtype: object
533번째 종목코드
종목코드    A021880
Name: 611, dtype: object
534번째 종목코드
종목코드    A022100
Name: 1734, dtype: object
535번째 종목코드
종목코드    A022220
Name: 215, dtype: object
536번째 종목코드
종목코드    A023000
Name: 765, dtype: object
537번째 종목코드
종목코드    A023150
Name: 147, dtype: object
538번째 종목코드
종목코드    A023160
Name: 1652, dtype: object
539번째 종목코드
종목코드    A023350
Name: 1832, dtype: object
540번째 종목코드
종목코드    A023410
Name: 1322, dtype: object
541번째 종목코드
종목코드    A023440
Name: 1450, dtype: object
542번째 종목코드
종목코드    A023450
Name: 465, dtype: object
543번째 종목코드
종목코드    A023460
Name: 21, dtype: object
544번째 종목코드
종목코드    A023530
Name: 570, dtype: object
545번째 종목코드
종목코드    A023590
Name: 368, dtype: object
546번째 종목코드
종목코드    A023600
Name: 736, dtype: object
547번째 종목코드
종목코드    A023760
Name: 1836, dtype: object
548번째 종목코드
종목코드    A023770
Name: 1764, dtype: object
549번째 종목코드
종목코드    A023800
Name: 1393, dtype: object
550번째 종목코드
종목코드    A023810
Name: 1405, dtype: object
551번째 종목코드
종목코드    A023900
Name: 1750, dtype: object
552번째 종목코드
종목코드    A023910
Name: 428, dtype: object
553번째 종목코드
종목코드    A023960
Name: 1093, dtype: object
554번째 종목코드
종목코드    A024060
Name: 1993, dtype: object
555번째 종목코드
종목코드    A024070
Name: 221, dtype: object
556번째 종목코드
종목코드    A024090
Name: 517, dtype: object
557번째 종목코드
종목코드    A024110
Name: 299, dtype: object
558번째 종목코드
종목코드    A024120
Name: 96, dtype: object
559번째 종목코드
종목코드    A024720
Name: 1839, dtype: object
560번째 종목코드
종목코드    A024740
Name: 1883, dtype: object
561번째 종목코드
종목코드    A024800
Name: 1313, dtype: object
562번째 종목코드
종목코드    A024810
Name: 1382, dtype: object
563번째 종목코드
종목코드    A024830
Name: 855, dtype: object
564번째 종목코드
종목코드    A024840
Name: 94, dtype: object
565번째 종목코드
종목코드    A024850
Name: 76, dtype: object
566번째 종목코드
종목코드    A024880
Name: 1569, dtype: object
567번째 종목코드
종목코드    A024890
Name: 412, dtype: object
568번째 종목코드
종목코드    A024900
Name: 450, dtype: object
569번째 종목코드
종목코드    A024910
Name: 246, dtype: object
570번째 종목코드
종목코드    A024940
Name: 161, dtype: object
571번째 종목코드
종목코드    A024950
Name: 778, dtype: object
572번째 종목코드
종목코드    A025000
Name: 116, dtype: object
573번째 종목코드
종목코드    A025320
Name: 907, dtype: object
574번째 종목코드
종목코드    A025440
Name: 31, dtype: object
575번째 종목코드
종목코드    A025530
Name: 184, dtype: object
576번째 종목코드
종목코드    A025540
Name: 1814, dtype: object
577번째 종목코드
종목코드    A025550
Name: 1819, dtype: object
578번째 종목코드
종목코드    A025560
Name: 641, dtype: object
579번째 종목코드
종목코드    A025750
Name: 1872, dtype: object
580번째 종목코드
종목코드    A025770
Name: 1831, dtype: object
581번째 종목코드
종목코드    A025820
Name: 1334, dtype: object
582번째 종목코드
종목코드    A025860
Name: 320, dtype: object
583번째 종목코드
종목코드    A025880
Name: 1557, dtype: object
584번째 종목코드
종목코드    A025900
Name: 501, dtype: object
585번째 종목코드
종목코드    A025950
Name: 473, dtype: object
586번째 종목코드
종목코드    A025980
Name: 975, dtype: object
587번째 종목코드
종목코드    A026040
Name: 1457, dtype: object
588번째 종목코드
종목코드    A026150
Name: 1678, dtype: object
589번째 종목코드
종목코드    A026890
Name: 901, dtype: object
590번째 종목코드
종목코드    A026940
Name: 691, dtype: object
591번째 종목코드
종목코드    A026960
Name: 469, dtype: object
592번째 종목코드
종목코드    A027050
Name: 1580, dtype: object
593번째 종목코드
종목코드    A027360
Name: 1022, dtype: object
594번째 종목코드
종목코드    A027410
Name: 6, dtype: object
595번째 종목코드
종목코드    A027580
Name: 788, dtype: object
596번째 종목코드
종목코드    A027710
Name: 1720, dtype: object
597번째 종목코드
종목코드    A027740
Name: 590, dtype: object
598번째 종목코드
종목코드    A027830
Name: 392, dtype: object
599번째 종목코드
종목코드    A027970
Name: 866, dtype: object
600번째 종목코드
종목코드    A028050
Name: 744, dtype: object
601번째 종목코드
종목코드    A028080
Name: 1982, dtype: object
602번째 종목코드
종목코드    A028100
Name: 477, dtype: object
603번째 종목코드
종목코드    A028260
Name: 740, dtype: object
604번째 종목코드
종목코드    A028300
Name: 72, dtype: object
605번째 종목코드
종목코드    A028670
Name: 1723, dtype: object
606번째 종목코드
종목코드    A029460
Name: 1553, dtype: object
607번째 종목코드
종목코드    A029480
Name: 264, dtype: object
608번째 종목코드
종목코드    A029530
Name: 914, dtype: object
609번째 종목코드
종목코드    A029780
Name: 751, dtype: object
610번째 종목코드
종목코드    A029960
Name: 1603, dtype: object
611번째 종목코드
종목코드    A030000
Name: 1462, dtype: object
612번째 종목코드
종목코드    A030190
Name: 156, dtype: object
613번째 종목코드
종목코드    A030200
Name: 120, dtype: object
614번째 종목코드
종목코드    A030210
Name: 367, dtype: object
615번째 종목코드
종목코드    A030350
Name: 509, dtype: object
616번째 종목코드
종목코드    A030520
Name: 1850, dtype: object
617번째 종목코드
종목코드    A030530
Name: 1265, dtype: object
618번째 종목코드
종목코드    A030610
Name: 267, dtype: object
619번째 종목코드
종목코드    A030960
Name: 1056, dtype: object
620번째 종목코드
종목코드    A031310
Name: 1013, dtype: object
621번째 종목코드
종목코드    A031330
Name: 1070, dtype: object
622번째 종목코드
종목코드    A031430
Name: 924, dtype: object
623번째 종목코드
종목코드    A031440
Name: 925, dtype: object
624번째 종목코드
종목코드    A031510
Name: 1205, dtype: object
625번째 종목코드
종목코드    A031820
Name: 1619, dtype: object
626번째 종목코드
종목코드    A031860
Name: 1143, dtype: object
627번째 종목코드
종목코드    A031980
Name: 1770, dtype: object
628번째 종목코드
종목코드    A032190
Name: 369, dtype: object
629번째 종목코드
종목코드    A032300
Name: 1845, dtype: object
630번째 종목코드
종목코드    A032350
Name: 568, dtype: object
631번째 종목코드
종목코드    A032500
Name: 1565, dtype: object
632번째 종목코드
종목코드    A032540
Name: 214, dtype: object
633번째 종목코드
종목코드    A032560
Name: 1966, dtype: object
634번째 종목코드
종목코드    A032580
Name: 1766, dtype: object
635번째 종목코드
종목코드    A032620
Name: 1309, dtype: object
636번째 종목코드
종목코드    A032640
Name: 132, dtype: object
637번째 종목코드
종목코드    A032680
Name: 878, dtype: object
638번째 종목코드
종목코드    A032750
Name: 773, dtype: object
639번째 종목코드
종목코드    A032790
Name: 1167, dtype: object
640번째 종목코드
종목코드    A032800
Name: 1717, dtype: object
641번째 종목코드
종목코드    A032820
Name: 1235, dtype: object
642번째 종목코드
종목코드    A032830
Name: 742, dtype: object
643번째 종목코드
종목코드    A032850
Name: 720, dtype: object
644번째 종목코드
종목코드    A032860
Name: 1983, dtype: object
645번째 종목코드
종목코드    A032940
Name: 1259, dtype: object
646번째 종목코드
종목코드    A032960
Name: 497, dtype: object
647번째 종목코드
종목코드    A032980
Name: 667, dtype: object
648번째 종목코드
종목코드    A033100
Name: 1447, dtype: object
649번째 종목코드
종목코드    A033130
Name: 539, dtype: object
650번째 종목코드
종목코드    A033160
Name: 1168, dtype: object
651번째 종목코드
종목코드    A033170
Name: 905, dtype: object
652번째 종목코드
종목코드    A033180
Name: 111, dtype: object
653번째 종목코드
종목코드    A033200
Name: 631, dtype: object
654번째 종목코드
종목코드    A033230
Name: 1389, dtype: object
655번째 종목코드
종목코드    A033240
Name: 1434, dtype: object
656번째 종목코드
종목코드    A033270
Name: 1293, dtype: object
657번째 종목코드
종목코드    A033290
Name: 1610, dtype: object
658번째 종목코드
종목코드    A033310
Name: 1170, dtype: object
659번째 종목코드
종목코드    A033320
Name: 1454, dtype: object
660번째 종목코드
종목코드    A033340
Name: 1490, dtype: object
661번째 종목코드
종목코드    A033500
Name: 472, dtype: object
662번째 종목코드
종목코드    A033530
Name: 859, dtype: object
663번째 종목코드
종목코드    A033540
Name: 1701, dtype: object
664번째 종목코드
종목코드    A033560
Name: 701, dtype: object
665번째 종목코드
종목코드    A033640
Name: 335, dtype: object
666번째 종목코드
종목코드    A033780
Name: 121, dtype: object
667번째 종목코드
종목코드    A033830
Name: 1681, dtype: object
668번째 종목코드
종목코드    A033920
Name: 637, dtype: object
669번째 종목코드
종목코드    A034020
Name: 505, dtype: object
670번째 종목코드
종목코드    A034120
Name: 168, dtype: object
671번째 종목코드
종목코드    A034220
Name: 130, dtype: object
672번째 종목코드
종목코드    A034230
Name: 1700, dtype: object
673번째 종목코드
종목코드    A034300
Name: 923, dtype: object
674번째 종목코드
종목코드    A034310
Name: 155, dtype: object
675번째 종목코드
종목코드    A034590
Name: 1394, dtype: object
676번째 종목코드
종목코드    A034730
Name: 185, dtype: object
677번째 종목코드
종목코드    A034810
Name: 1909, dtype: object
678번째 종목코드
종목코드    A034830
Name: 1843, dtype: object
679번째 종목코드
종목코드    A034940
Name: 1483, dtype: object
680번째 종목코드
종목코드    A034950
Name: 1812, dtype: object
681번째 종목코드
종목코드    A035000
Name: 1511, dtype: object
682번째 종목코드
종목코드    A035080
Name: 279, dtype: object
683번째 종목코드
종목코드    A035150
Name: 674, dtype: object
684번째 종목코드
종목코드    A035250
Name: 232, dtype: object
685번째 종목코드
종목코드    A035290
Name: 257, dtype: object
686번째 종목코드
종목코드    A035420
Name: 148, dtype: object
687번째 종목코드
종목코드    A035460
Name: 296, dtype: object
688번째 종목코드
종목코드    A035510
Name: 922, dtype: object
689번째 종목코드
종목코드    A035600
Name: 109, dtype: object
690번째 종목코드
종목코드    A035610
Name: 882, dtype: object
691번째 종목코드
종목코드    A035620
Name: 659, dtype: object
692번째 종목코드
종목코드    A035720
Name: 1537, dtype: object
693번째 종목코드
종목코드    A035760
Name: 14, dtype: object
694번째 종목코드
종목코드    A035810
Name: 1376, dtype: object
695번째 종목코드
종목코드    A035890
Name: 823, dtype: object
696번째 종목코드
종목코드    A035900
Name: 92, dtype: object
697번째 종목코드
종목코드    A036000
Name: 1185, dtype: object
698번째 종목코드
종목코드    A036010
Name: 985, dtype: object
699번째 종목코드
종목코드    A036030
Name: 1566, dtype: object
700번째 종목코드
종목코드    A036090
Name: 1288, dtype: object
701번째 종목코드
종목코드    A036120
Name: 171, dtype: object
702번째 종목코드
종목코드    A036170
Name: 1638, dtype: object
703번째 종목코드
종목코드    A036190
Name: 294, dtype: object
704번째 종목코드
종목코드    A036200
Name: 1295, dtype: object
705번째 종목코드
종목코드    A036420
Name: 1617, dtype: object
706번째 종목코드
종목코드    A036460
Name: 1808, dtype: object
707번째 종목코드
종목코드    A036480
Name: 389, dtype: object
708번째 종목코드
종목코드    A036530
Name: 206, dtype: object
709번째 종목코드
종목코드    A036540
Name: 173, dtype: object
710번째 종목코드
종목코드    A036560
Name: 1180, dtype: object
711번째 종목코드
종목코드    A036570
Name: 1142, dtype: object
712번째 종목코드
종목코드    A036580
Name: 1719, dtype: object
713번째 종목코드
종목코드    A036620
Name: 229, dtype: object
714번째 종목코드
종목코드    A036630
Name: 861, dtype: object
715번째 종목코드
종목코드    A036640
Name: 82, dtype: object
716번째 종목코드
종목코드    A036670
Name: 100, dtype: object
717번째 종목코드
종목코드    A036690
Name: 1585, dtype: object
718번째 종목코드
종목코드    A036710
Name: 943, dtype: object
719번째 종목코드
종목코드    A036800
Name: 314, dtype: object
720번째 종목코드
종목코드    A036810
Name: 1132, dtype: object
721번째 종목코드
종목코드    A036830
Name: 884, dtype: object
722번째 종목코드

## #4

In [ ]:
idx=464+232

In [ ]:
for c in sliced_dataframes[idx:2*idx]:
  print(labels.iloc[idx])
  print("{}번째 종목코드".format(idx))
  trans_model=Transformer(data=c,idx=idx,day='230727_1')
  pred,gap = trans_model.return_val()
  sleep(1)
  pred_list.append(pred)
  gap_acc.append(gap)
  idx+=1
  #to prevent model corrupting
pred_csv_df=pd.DataFrame(
  {
  '종가':pred_list,
  'gap':gap_acc
  },
  index=[i for i in range(idx,idx+232)],
  columns=['종가','gap']
)
pred_csv_df.to_csv('/content/drive/MyDrive/2023_1st_vac/KRX_modelings/predicitions/{}.csv'.format("230725_v0.4"),index=True)

## #5

In [ ]:
idx=464+232+232
for c in sliced_dataframes[idx:2*idx]:
  print(labels.iloc[idx])
  print("{}번째 종목코드".format(idx))
  trans_model=Transformer(data=c,idx=idx,day='230727_1')
  pred,gap = trans_model.return_val()
  sleep(1)
  pred_list.append(pred)
  gap_acc.append(gap)
  idx+=1
  #to prevent model corrupting
pred_csv_df=pd.DataFrame(
  {
  '종가':pred_list,
  'gap':gap_acc
  },
  index=[i for i in range(idx,idx+232)],
  columns=['종가','gap']
)
pred_csv_df.to_csv('/content/drive/MyDrive/2023_1st_vac/KRX_modelings/predicitions/{}.csv'.format("230725_v0.5"),index=True)

## #6

In [ ]:
idx=464+464+232
for c in sliced_dataframes[idx:2*idx]:
  print(labels.iloc[idx])
  print("{}번째 종목코드".format(idx))
  trans_model=Transformer(data=c,idx=idx,day='230727_1')
  pred,gap = trans_model.return_val()
  sleep(1)
  pred_list.append(pred)
  gap_acc.append(gap)
  idx+=1
  #to prevent model corrupting
pred_csv_df=pd.DataFrame(
  {
  '종가':pred_list,
  'gap':gap_acc
  },
  index=[i for i in range(idx,idx+232)],
  columns=['종가','gap']
)
pred_csv_df.to_csv('/content/drive/MyDrive/2023_1st_vac/KRX_modelings/predicitions/{}.csv'.format("230725_v0.6"),index=True)

## #7

In [ ]:
idx=464+464+464
for c in sliced_dataframes[idx:2*idx]:
  print(labels.iloc[idx])
  print("{}번째 종목코드".format(idx))
  trans_model=Transformer(data=c,idx=idx,day='230727_1')
  pred,gap = trans_model.return_val()
  sleep(1)
  pred_list.append(pred)
  gap_acc.append(gap)
  idx+=1
  #to prevent model corrupting
pred_csv_df=pd.DataFrame(
  {
  '종가':pred_list,
  'gap':gap_acc
  },
  index=[i for i in range(idx,idx+232)],
  columns=['종가','gap']
)
pred_csv_df.to_csv('/content/drive/MyDrive/2023_1st_vac/KRX_modelings/predicitions/{}.csv'.format("230725_v0.7"),index=True)

## #8

In [ ]:
idx=(464*3)+232
for c in sliced_dataframes[idx:idx+232]:
  print(labels.iloc[idx])
  print("{}번째 종목코드".format(idx))
  trans_model=Transformer(data=c,idx=idx,day='230727_1')
  pred,gap = trans_model.return_val()
  sleep(1)
  pred_list.append(pred)
  gap_acc.append(gap)
  idx+=1
  #to prevent model corrupting
pred_csv_df=pd.DataFrame(
  {
  '종가':pred_list,
  'gap':gap_acc
  },
  index=[i for i in range(idx,idx+232)],
  columns=['종가','gap']
)
pred_csv_df.to_csv('/content/drive/MyDrive/2023_1st_vac/KRX_modelings/predicitions/{}.csv'.format("230725_v0.8"),index=True)

## #9

In [ ]:
idx=(464*4)
for c in sliced_dataframes[idx:idx+232]:
  print(labels.iloc[idx])
  print("{}번째 종목코드".format(idx))
  trans_model=Transformer(data=c,idx=idx,day='230727_1')
  pred,gap = trans_model.return_val()
  sleep(1)
  pred_list.append(pred)
  gap_acc.append(gap)
  idx+=1
  #to prevent model corrupting
pred_csv_df=pd.DataFrame(
  {
  '종가':pred_list,
  'gap':gap_acc
  },
  index=[i for i in range(idx,idx+232)],
  columns=['종가','gap']
)
pred_csv_df.to_csv('/content/drive/MyDrive/2023_1st_vac/KRX_modelings/predicitions/{}.csv'.format("230725_v0.9"),index=True)